name: prek Autoupdate

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

jobs:
  prek-autoupdate:
    uses: ./.github/workflows/prek_autoupdate.yml
    permissions:
      contents: write
      pull-requests: write
      actions: write
    with:
      dispatch-workflows: |
        linters.yml
        pytest_coverage.yml
