name: prek Autoupdate

on:
  schedule:
    - cron: "0 4 * * 1"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prek-autoupdate:
    uses: ./.github/workflows/prek_autoupdate.yml
    permissions:
      contents: write
      pull-requests: write
